<?php $data = $_SESSION['visitData'] ?? ($visit ?? []);
unset($_SESSION['visitData']); ?>
<div class="grid gap-5 md:grid-cols-2"><label class="text-sm font-medium">Family<select name="family_id" required class="mt-2 w-full rounded-lg border border-slate-300 p-2.5">

			<option value="">Select</option><?php foreach ($families as $f): ?><option value="<?= (int)$f['family_id'] ?>" <?= (string)($data['family_id'] ?? '') === (string)$f['family_id'] ? 'selected' : '' ?>><?= e($f['registration_number']) ?></option><?php endforeach; ?>
		</select></label><label class="text-sm font-medium">Staff member<select name="staff_id" required class="mt-2 w-full rounded-lg border border-slate-300 p-2.5">
			<option value="">Select</option><?php foreach ($staff as $s): ?><option value="<?= (int)$s['staff_id'] ?>" <?= (string)($data['staff_id'] ?? '') === (string)$s['staff_id'] ? 'selected' : '' ?>><?= e($s['full_name']) ?></option><?php endforeach; ?>
		</select></label><label class="text-sm font-medium">Person (optional)<select name="person_id" class="mt-2 w-full rounded-lg border border-slate-300 p-2.5">
			<option value="">Whole family</option><?php foreach ($people as $p): ?><option value="<?= (int)$p['person_id'] ?>" <?= (string)($data['person_id'] ?? '') === (string)$p['person_id'] ? 'selected' : '' ?>><?= e($p['full_name']) ?></option><?php endforeach; ?>
		</select></label><label class="text-sm font-medium">Visit date<input type="date" name="visit_date" required value="<?= e($data['visit_date'] ?? '') ?>" class="mt-2 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Visit type<select name="visit_type" class="mt-2 w-full rounded-lg border border-slate-300 p-2.5"><?php foreach (['Routine', 'Follow-up', 'Emergency', 'Postnatal', 'Child Welfare'] as $v): ?><option <?= ($data['visit_type'] ?? '') === $v ? 'selected' : '' ?>><?= e($v) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Status<select name="visit_status" class="mt-2 w-full rounded-lg border border-slate-300 p-2.5"><?php foreach (['Completed', 'Cancelled', 'Rescheduled'] as $v): ?><option <?= ($data['visit_status'] ?? 'Completed') === $v ? 'selected' : '' ?>><?= e($v) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Follow-up date<input type="date" name="follow_up_date" value="<?= e($data['follow_up_date'] ?? '') ?>" class="mt-2 w-full rounded-lg border border-slate-300 p-2.5"></label>
	<div class="flex items-end gap-6"><label><input type="checkbox" name="follow_up_required" value="1" <?= !empty($data['follow_up_required']) ? 'checked' : '' ?>> Follow-up required</label><label><input type="checkbox" name="risk_identified" value="1" <?= !empty($data['risk_identified']) ? 'checked' : '' ?>> Risk identified</label></div><label class="text-sm font-medium md:col-span-2">Observations<textarea name="observations" rows="4" class="mt-2 w-full rounded-lg border border-slate-300 p-2.5"><?= e($data['observations'] ?? '') ?></textarea></label>
</div>
<div class="mt-6 flex gap-3"><button class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Save Visit</button><a href="<?= APP_URL ?>/field-visits" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm">Cancel</a></div>