<?php
$record=$record??[];$oldData=$_SESSION['vaccinationData']??[];unset($_SESSION['vaccinationData']);
$value=static fn(string $key,mixed $default=''):mixed=>array_key_exists($key,$oldData)?$oldData[$key]:($record[$key]??$default);
$class='mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500';
?>
<form method="post" action="<?= e($formAction) ?>" class="space-y-6"><section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-4"><h2 class="font-semibold text-slate-900"><?= e($child['full_name']) ?></h2><p class="text-sm text-slate-500">Record the vaccine, dose, batch and administration details.</p></div><div class="grid gap-5 p-6 md:grid-cols-2">
<label class="text-sm font-medium text-slate-700">Vaccine and dose<select required name="schedule_id" class="<?= $class ?>"><option value="">Select vaccine</option><?php foreach($schedules??[] as $s): ?><option value="<?= (int)$s['schedule_id'] ?>" <?= (int)$value('schedule_id')===(int)$s['schedule_id']?'selected':'' ?>><?= e($s['vaccine_name'].' · dose '.$s['dose_number'].' · '.$s['description']) ?></option><?php endforeach; ?></select></label>
<label class="text-sm font-medium text-slate-700">Administered by<select required name="administered_by" class="<?= $class ?>"><option value="">Select staff</option><?php foreach($staff??[] as $s): ?><option value="<?= (int)$s['staff_id'] ?>" <?= (int)$value('administered_by')===(int)$s['staff_id']?'selected':'' ?>><?= e($s['full_name']) ?></option><?php endforeach; ?></select></label>
<label class="text-sm font-medium text-slate-700">Vaccination date<input required type="date" name="vaccination_date" value="<?= e($value('vaccination_date',date('Y-m-d'))) ?>" class="<?= $class ?>"></label>
<label class="text-sm font-medium text-slate-700">Batch number<input name="batch_number" maxlength="50" value="<?= e($value('batch_number')) ?>" class="<?= $class ?>"></label>
<label class="text-sm font-medium text-slate-700">Next due date<input type="date" name="next_due_date" value="<?= e($value('next_due_date')) ?>" class="<?= $class ?>"></label>
<label class="text-sm font-medium text-slate-700">Status<select required name="vaccination_status" class="<?= $class ?>"><?php foreach(['Completed','Delayed','Missed','Contraindicated'] as $status): ?><option <?= $value('vaccination_status','Completed')===$status?'selected':'' ?>><?= e($status) ?></option><?php endforeach; ?></select></label>
<label class="flex items-center gap-3 text-sm font-medium text-slate-700"><input type="checkbox" name="adverse_event_reported" value="1" <?= $value('adverse_event_reported')?'checked':'' ?> class="rounded border-slate-300 text-blue-600">Adverse event reported</label><span></span>
<label class="text-sm font-medium text-slate-700">Side effects<textarea name="side_effects" rows="3" class="<?= $class ?>"><?= e($value('side_effects')) ?></textarea></label><label class="text-sm font-medium text-slate-700">Remarks<textarea name="remarks" rows="3" class="<?= $class ?>"><?= e($value('remarks')) ?></textarea></label>
</div></section><div class="flex justify-end gap-3"><a href="<?= e(APP_URL.'/children/'.(int)$child['person_id'].'/vaccinations') ?>" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white"><?= e($submitLabel) ?></button></div></form>
